language: java
jdk:
- oraclejdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: WkC1NuCjagiUTic1qyBYNxyGCx9Ak8I7u+qzCOcnvATHTMryD8c7S3LZdqqjVqpYESAWVrS/4be+pDUS8o68R0sIDYHbqTvF9ArxckNwkoWsj/SkdgV99ZaKyZWz/NerJaTeq0jX0dBrO5SY94abcF6Yxo1RdPOcl9dlelW+7TQ=
  - secure: M213jazhnnX87+y+p6TbVoOzhLlJu+EzHE9/5v5rZxedUO9jUhIfNBSVq8pjiCFaf08t8wUiGiQbOwMkd/x7iOiaQOg+JjvLSwFPquIJac2st9T8U4PSOFOuJyrTH1NHO7g2oldxFeYds0L1NTfZM5ynv6x0Cs63nOciPS2m/2A=
  - secure: cJtr+DcUiyUKiGjuBf6g5hrpsoNWZmOAr4Bp3BdX1imaAfPGI0LwFgyOlSkXCx57ZlGLARS9u2+toNgcvaFo3x5m+66xPACebG56s1h4pRsY724o6LGs27KedE7s41wA9e2+GAltQOTZ+FO68sNw1wqQoFx0f7CZhjPyRvJqLtU=
  - secure: jeKDnoLxbubf7hTXAmHQdrlUe8gCQZ04vTTrtcie77s5Mmv4vUHR0NfLr3HPoYSzW9J/zYK8m9S/ZUJpTqpJwUg7yVNl4fsCYzzkM+mIguZGhS5yxp6F48GHX9hR6bIk1YS22CPkq2O7/AubjgxzpiP3XizL2MZnaMUAfB7WMvw=
cache:
  directories:
  - "$HOME/.gradle/caches"
